ranks:
  InsertRankHere:
    playTimeNeeded: 5
    promoteTo: NewRankHere
  AnotherRankHere:
    playTimeNeeded: 5
    promoteTo: NewRankHere
  NonPromotingRank:
    noPromote: true

defaultPromote:
  default: DefaultRankHere
  promoteTo: NewRankHere

settings:
  saveTime: 10
  debug: false