author: ZephireNZ
database: false
main: me.ZephireNZ.NoirlandAutoPromote.NoirlandAutoPromote
name: NoirlandAutoPromote
startup: postworld
version: 1.0
depend: [SQLibrary, GroupManager]
commands:
    autopromote:
        description: Check when you other others will be promoted.
        usage: |
          Usage:
          /<command> (player)
permissions:
    autopromote.*:
      description: Access to all autopromote commands.
      default: op
      children:
        autopromote.check: true
        autopromote.check.others: true
    autopromote.check:
      description: Check own promotion info.
      default: true
    autopromote.check.others:
      description: Check anothers promotion info.
      default: op
      children:
        autopromote.check: true