author: ZephireNZ
database: false
main: me.ZephireNZ.NoirlandAutoPromote.NoirlandAutoPromote
name: NoirlandAutoPromote
startup: postworld
version: 1.1
depend: [SQLibrary, GroupManager]
commands:
    autopromote:
        description: Check when you other others will be promoted.
        usage: |
          Usage:
          /<command> (player) - check player play time
          /<command> promote (player) - promotes player by one step
          /<command> promote (player) (rank) - Promote player to rank (and annouces in game). RANK IS CASE SENSITIVE
          /<command> reload - Reloads the config file, among other things.
permissions:
    autopromote.*:
      description: Access to all autopromote commands.
      default: op
      children:
        autopromote.check: true
        autopromote.check.others: true
    autopromote.check:
      description: Check own promotion info.
      default: true
    autopromote.check.others:
      description: Check anothers promotion info.
      default: op
      children:
        autopromote.check: true