author: ZephireNZ
database: false
main: me.ZephireNZ.NoirlandAutoPromote.NoirlandAutoPromote
name: NoirlandAutoPromote
startup: postworld
version: 1.23
depend: [SQLibrary, GroupManager]
commands:
    autopromote:
      aliases: [noirpromote]
      description: Check when you other others will be promoted.
permissions:
    autopromote.*:
      description: Access to all autopromote commands.
      default: op
      children:
        autopromote.check: true
        autopromote.check.others: true
        autopromote.reload: true
        autopromote.promote: true
        autopromote.reset: true
    autopromote.check:
      description: Check own promotion info.
      default: true
    autopromote.check.others:
      description: Check anothers promotion info.
      default: op
      children:
        autopromote.check: true
    autopromote.reload:
      description: Reload the plugin
      default: op
    autopromote.promote:
      description: Promote a player
      default: op
    autopromote.reset:
      description: Reset a players Play Time
      default: op