ranks:
  DefaultRankHere:
    noPromote: true
    default: true
    promoteTo: NewRankHere
  InsertRankHere:
    playTimeNeeded: 5
    promoteTo: NewRankHere
  AnotherRankHere:
    playTimeNeeded: 5
    promoteTo: NewRankHere
  NonPromotingRank:
    noPromote: true

defaultPromote:
  default: DefaultRankHere
  promoteTo: NewRankHere

settings:
  saveTime: 10
  sortTime 5
  debug: false