ranks:
  DefaultRankHere:
    noPromote: true
    default: true
    promoteTo: NewRankHere
  InsertRankHere:
    playTimeNeeded: 5
    promoteTo: NewRankHere
  AnotherRankHere:
    playTimeNeeded: 5
    female: FemaleRank
    promoteTo: NewRankHere
  NonPromotingRank:
    noPromote: true
    female: NonPromotingFemaleRank

defaultPromote:
  default: DefaultRankHere
  promoteTo: NewRankHere

settings:
  saveTime: 10
  debug: false