ranks:
  DefaultRankHere:
    noPromote: true
    default: true
    promoteTo: NewRankHere
  InsertRankHere:
    playTimeNeeded: 5
    promoteTo: NewRankHere
  AnotherRankHere:
    playTimeNeeded: 5
    promoteTo: NewRankHere
  NonPromotingRank:
    noPromote: true

mysql:
    database: autopromote
    username: autopromote
    password: 'password'
    port: 3306
    host: localhost
    prefix: promote

settings:
  saveTime: 10
  sortTime: 5